//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18051
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MySbbInfo.Modules.TravelCardModule.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Translation_us_en {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Translation_us_en() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MySbbInfo.Modules.TravelCardModule.Properties.Translation.us-en", typeof(Translation_us_en).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;- Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bill.
        /// </summary>
        public static string Bill {
            get {
                return ResourceManager.GetString("Bill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available payment options:.
        /// </summary>
        public static string ChoosePaymentOption {
            get {
                return ResourceManager.GetString("ChoosePaymentOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose the right travel option offer for you:.
        /// </summary>
        public static string ChooseTravelOption {
            get {
                return ResourceManager.GetString("ChooseTravelOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditcard Security Code.
        /// </summary>
        public static string CreditCardCode {
            get {
                return ResourceManager.GetString("CreditCardCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creditcard Nr..
        /// </summary>
        public static string CreditCardNr {
            get {
                return ResourceManager.GetString("CreditCardNr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GA   (3550.- CHF).
        /// </summary>
        public static string GAOption {
            get {
                return ResourceManager.GetString("GAOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flexible and independent: with a GA travelcard, you simply get aboard the next train. The GA travelcard is available in both 1st and 2nd class.
        ///
        ///Throughout its period of validity, you enjoy free travel on all SBB routes, and also those of most private rail companies, throughout Switzerland. The GA travelcard is also valid for postbuses and boats, as well as for short-distance public transport services like trams and buses in most cities and urban areas. And it gives you special discounts on many Swiss mou [rest of string was truncated]&quot;;.
        /// </summary>
        public static string GAOptionDescription {
            get {
                return ResourceManager.GetString("GAOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half-Fare   (175.- CHF).
        /// </summary>
        public static string HalfPriceOption {
            get {
                return ResourceManager.GetString("HalfPriceOption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The Half-Fare travelcard is available for 1, 2 or 3 years and allows you to buy 1st or 2nd class tickets for just half* the price.
        ///
        ///There is also a Half-Fare travelcard combined with a free Visa credit card or a Visa prepaid card: You can travel by train at low cost in Switzerland and pay conveniently and without cash when abroad using just one card.
        ///
        ///Order your Half-Fare travelcard at your station or on the Internet at SBB Ticket Shop.
        ///
        ///The Half-Fare travelcard is even more attractive with the add-on [rest of string was truncated]&quot;;.
        /// </summary>
        public static string HalfPriceOptionDescription {
            get {
                return ResourceManager.GetString("HalfPriceOptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next -&gt;.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Street.
        /// </summary>
        public static string Street {
            get {
                return ResourceManager.GetString("Street", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Track 7   (129.- CHF).
        /// </summary>
        public static string Track7Option {
            get {
                return ResourceManager.GetString("Track7Option", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you under 25, a Half-Fare travelcard holder and happy to travel in the evenings? Then Track 7 is ideal for you.
        ///
        ///Track 7 entitles you to take any journeys in 2nd class from 7.00 p.m. to 5.00 a.m. – on the entire SBB network as well as with numerous private transport companies. Important: The night supplement is not included in Track 7 and you must purchase this additionally.
        ///
        ///The area of validity shows you where you may use Track 7.
        ///
        ///Discover the exciting, interactive world of Track 7 at www.gleis [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Track7OptionDescription {
            get {
                return ResourceManager.GetString("Track7OptionDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Travelcards.
        /// </summary>
        public static string Travelcards {
            get {
                return ResourceManager.GetString("Travelcards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your choice:.
        /// </summary>
        public static string YourChoice {
            get {
                return ResourceManager.GetString("YourChoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip.
        /// </summary>
        public static string Zip {
            get {
                return ResourceManager.GetString("Zip", resourceCulture);
            }
        }
    }
}
